# Path to your oh-my-zsh installation.
export ZSH=/Users/irfansharif/.oh-my-zsh
DEFAULT_USER="Irfan"

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# Preferred options: robbyrussell, soliah, kafeitu, gallifrey, nebirhos,
# philips, cypher, dstufft, risto, half-life, jbergantine, norm, essembeh
# fina (should be personalized more), murilasso, nebirhos
ZSH_THEME="jbergantine"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="dd.mm.yyyy"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(zsh-autosuggestions git colored-man-pages history knife rails ruby rbenv)
# User configuration

export PATH="/Users/irfansharif/.rbenv/bin:/Users/irfansharif/.rbenv/shims:/usr/local/sbin:/usr/sbin:/sbin:/opt/local/bin:/opt/local/sbin:~/torch/install/bin:/Users/irfansharif/github/install/bin/torch-activate:/Developer/NVIDIA/CUDA-7.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"

source $ZSH/oh-my-zsh.sh

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
else
   export EDITOR='vim'
fi

# Autojump config for OSX
[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh
# Zsh autosuggestions binding

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
# Example aliases
alias zshconfig="vim ~/.zshrc"
alias ohmyzsh="vim ~/.oh-my-zsh"
alias tmux="TERM=screen-256color-bce tmux"
alias cdrd="cd $(git rev-parse --show-toplevel)"
alias cl=clear

export PATH="/usr/local/go/bin:$PATH"
[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

bindkey '`' autosuggest-accept
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE=fg=3  # Options: 1, 2, 3, 4
ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=("expand-or-complete")
unsetopt correct

source /Users/irfansharif/code/github/zaw/zaw.zsh

ruby ~/code/github/dotfiles/tmux/start-tmux.rb
